---

-  hosts : all
   become: true
   name: 6-playbook-remove-webservers
   tasks:
     - name: un-install Apache
       apt:
           name: apache2
           state: absent
           autoremove: yes
           purge: yes

-  hosts : test
   become: true
   name: 5-playbook-remove-webservers
   tasks:
     - name: un-install Nginx
       apt:
           name: nginx-common
           state: absent